### ISSUE TITLE
Timeline display issues (Chrome)

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/opendata-web#1]
On MacOS Chrome 64 (haven't tested other versions) the timeline bar is displayed on top and not the bottom (as it should be).

<img width="1680" alt="screen shot 2018-03-01 at 17 21 58" src="https://user-images.githubusercontent.com/54409/36853090-2c2dd0c6-1d76-11e8-8d5e-fca201a97f42.png">

**Comment by markko1-pro** [comment]
Should be fixed now
